# Generated by Django 4.0.2 on 2022-02-02 08:50

from django.db import migrations, models
import taskool.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(default='/questions/defualt.jpg', upload_to=taskool.models.upload_to, verbose_name='Image'),
        ),
    ]
