# Generated by Django 4.0.2 on 2022-02-02 09:34

from django.db import migrations, models
import taskool.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0002_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to=taskool.models.upload_to, verbose_name='Image'),
        ),
    ]
