# Generated by Django 4.0.2 on 2022-02-04 05:46

import django.core.validators
from django.db import migrations, models
import taskool.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0003_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.FileField(null=True, upload_to=taskool.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])], verbose_name='Audio'),
        ),
    ]
