# Generated by Django 4.0.2 on 2022-02-04 08:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taskool.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0004_question_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=255)),
                ('content', models.FileField(upload_to=taskool.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'jpg', 'jpeg', 'img', 'png'])])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.AddField(
            model_name='question',
            name='files',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskool.questionfile'),
            preserve_default=False,
        ),
    ]
