# Generated by Django 4.0.2 on 2022-02-04 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0005_questionfile_remove_question_audio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='files',
        ),
        migrations.AddField(
            model_name='questionfile',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskool.question'),
            preserve_default=False,
        ),
    ]
