# Generated by Django 4.0.2 on 2022-02-04 10:27

import django.core.validators
from django.db import migrations, models
import taskool.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0006_remove_question_files_questionfile_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='files',
            field=models.FileField(default=1, upload_to=taskool.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'jpg', 'jpeg', 'img', 'png'])]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='QuestionFile',
        ),
    ]
