# Generated by Django 4.0.2 on 2022-02-04 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taskool.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0008_remove_question_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=1000)),
                ('files', models.FileField(upload_to=taskool.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'jpg', 'jpeg', 'img', 'png'])])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskool.question')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
