# Generated by Django 4.0.2 on 2022-02-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0009_questionfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionfile',
            old_name='files',
            new_name='media',
        ),
        migrations.RemoveField(
            model_name='questionfile',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='questionfile',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='file_content',
            field=models.ManyToManyField(blank=True, null=True, to='taskool.QuestionFile'),
        ),
    ]
