# Generated by Django 4.0.2 on 2022-02-05 14:23

import django.core.validators
from django.db import migrations, models
import taskool.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0010_rename_files_questionfile_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('media', models.FileField(upload_to=taskool.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'jpg', 'jpeg', 'img', 'png'])])),
                ('extension', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='QuestionFile',
        ),
        migrations.AlterField(
            model_name='question',
            name='file_content',
            field=models.ManyToManyField(blank=True, null=True, to='taskool.File'),
        ),
    ]
