# Generated by Django 4.0.2 on 2022-02-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0011_file_delete_questionfile_alter_question_file_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-id']},
        ),
    ]
