# Generated by Django 4.0.2 on 2022-02-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0012_alter_file_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file_content',
            field=models.ManyToManyField(blank=True, null=True, related_name='file', to='taskool.File'),
        ),
    ]
