# Generated by Django 4.0.2 on 2022-02-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0014_alter_question_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_content',
            field=models.ManyToManyField(to='taskool.Question'),
        ),
    ]
