# Generated by Django 4.0.2 on 2022-02-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0015_file_file_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_content',
        ),
        migrations.AddField(
            model_name='option',
            name='explanation',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='file_content',
            field=models.ManyToManyField(to='taskool.File'),
        ),
    ]
