# Generated by Django 4.0.2 on 2022-02-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0016_remove_file_file_content_option_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
