# Generated by Django 4.0.2 on 2022-02-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0018_answer_question_is_option_based_textanswer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='audioanswer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='textanswer',
            options={'ordering': ['-id']},
        ),
    ]
