# Generated by Django 4.0.2 on 2022-02-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0020_alter_audioanswer_options_alter_textanswer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audioanswer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='textanswer',
            options={'ordering': ['-id']},
        ),
    ]
