# Generated by Django 4.0.2 on 2022-02-08 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0022_alter_audioanswer_options_alter_textanswer_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='audio_answer',
        ),
    ]
