# Generated by Django 4.0.2 on 2022-02-08 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0023_remove_answer_audio_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='audio_answer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskool.audioanswer'),
            preserve_default=False,
        ),
    ]
