# Generated by Django 4.0.2 on 2022-02-08 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0024_answer_audio_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='audio_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_answer', to='taskool.audioanswer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_answer', to='taskool.textanswer'),
        ),
    ]
