# Generated by Django 4.0.2 on 2022-02-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0025_alter_answer_audio_answer_alter_answer_text_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('teacher', models.BooleanField(default=False)),
                ('student', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='audioanswer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='textanswer',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='audio_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taskool.audioanswer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='taskool.textanswer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskool.user'),
        ),
    ]
