# Generated by Django 4.0.2 on 2022-02-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0027_alter_answer_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='audio_answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskool.audioanswer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='taskool.textanswer'),
        ),
    ]
