# Generated by Django 4.0.2 on 2022-02-10 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskool', '0029_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskool.quiz'),
            preserve_default=False,
        ),
    ]
